{
 "title": "JUNO Stats",
 "time": { "from": "2025-02-13T15:41:34.921Z", "to": "2025-02-13T15:42:21.846Z" },
 "refresh": "5s",
 "panels": [
  {
   "title": "JUNO sensors, actuators and position",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "LiDAR readings",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "dataset": "rover_control",
     "rawSql": "SELECT distance_front, distance_left, distance_right, timestamp FROM rover_control.lidar_readings ORDER BY timestamp DESC LIMIT 50 "
    }
   ]
  },
  {
   "title": "JUNO Position",
   "type": "xychart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "dataset": "rover_control",
     "rawSql": "SELECT x, y FROM rover_control.rover_position ORDER BY timestamp DESC LIMIT 50 "
    }
   ]
  },
  {
   "title": "Gyroscope readings",
   "type": "status-history",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "dataset": "rover_control",
     "rawSql": "SELECT timestamp, angle_x, angle_y, angle_z FROM rover_control.gyro_readings ORDER BY timestamp DESC LIMIT 50 "
    }
   ]
  },
  {
   "title": "Direction commands executed by leg's servo motors",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "dataset": "rover_control",
     "rawSql": "SELECT timestamp, new_direction FROM rover_control.leg_commands ORDER BY timestamp DESC LIMIT 50 "
    }
   ]
  },
  {
   "title": "Harpoon states",
   "type": "state-timeline",
   "description": "1 (Red) -> Dangerous inclination, Harpoons activated\n2 (Green) -> Acceptable Inclination, Harpoons not active",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "dataset": "rover_control",
     "rawSql": "SELECT timestamp, fire FROM rover_control.harpoon_commands ORDER BY timestamp DESC LIMIT 50 "
    }
   ]
  }
 ]
}