{
 "title": "JUNO Stats",
 "time": { "from": "2025-02-04T15:18:19.799Z", "to": "2025-02-04T15:27:15.856Z" },
 "refresh": "5s",
 "panels": [
  {
   "title": "LiDAR-Servo Motors on Robotic Legs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Distances in direction front, right and left",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "dataset": "rover_control",
     "rawSql": "SELECT distance_front, distance_left, distance_right, timestamp FROM rover_control.lidar_readings ORDER BY timestamp DESC LIMIT 50 "
    }
   ]
  },
  {
   "title": "JUNO Position",
   "type": "xychart",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "dataset": "rover_control",
     "rawSql": "SELECT x, y FROM rover_control.rover_position ORDER BY timestamp DESC LIMIT 50 "
    }
   ]
  },
  {
   "title": "Direction commands executed by leg's servo motors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "dataset": "rover_control",
     "rawSql": "SELECT timestamp, new_direction FROM rover_control.leg_commands ORDER BY timestamp DESC LIMIT 50 "
    }
   ]
  }
 ]
}